[build]
  publish = "."

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# This ensures that if someone types /ed.html, 
# they are permanently redirected to the clean /ed (Better for SEO)
[[redirects]]
  from = "/*.html"
  to = "/:splat"
  status = 301
  force = true